#!/usr/bin/env python
import xmltodict
import subprocess

def find_free_gpus():
    stdout = subprocess.check_output(('nvidia-smi', '-q', '-x'))
    X = xmltodict.parse(stdout)

    idxs = []
    for idx, gpu in enumerate(X['nvidia_smi_log']['gpu']):
        if gpu['processes'] is None:
            idxs.append(idx)
    return idxs

if __name__ == '__main__':
    print(' '.join([str(idx) for idx in find_free_gpus()]))
